- name: Backout change package
  stepName: ChangePackage
  description: Backout a change package to reverse a migration event
  endpoint: '/some/endpoint'
  method: POST
  $ref: REUSE/basic_procedure_config.yaml
  resultProperty:
    default: /myJob/changePackage
    $ref: REUSE/basic_result_property_config.yaml
  parameters:
    - property: Change Package
      Label: Change Package
      documentation: |-
        The name of the change package to be backed out
      in: body
      type: entry
      required: 1
    - property: Migration Scheme
      Label: Migration Scheme
      documentation: |-
        The name of the migration scheme used in the migration event that is to be backed out
      in: body
      type: entry
      required: 1