
// Was generated by REST Plugin Wizard
def procName = 'Ready change package'
def stepName = 'ReadyPackage'
procedure procName, description: 'Ready a change package for migration', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('ReadyPackage');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
